name: "Dagger on Ubicloud"

on:
  workflow_call:

jobs:
  run:
    runs-on: ubicloud-standard-2
    steps:
      - name: "Checkout code..."
        uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache-dependency-path: "magefiles/go.sum"

      - name: root suid tar
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
    
      - uses: actions/cache@v4
        with:
          path: /cache
          key: ${{ runner.os }}-cachekey2-${{ hashFiles('magefiles/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: "Provision Dagger with local cache"
        run: |
          docker run \
            --name dagger-0-6-4 \
            --detach --restart always \
            --volume /cache/dagger-0-6-4:/var/lib/dagger \
            --privileged \
            registry.dagger.io/engine:v0.6.4

      - name: "Build, test, publish & deploy..."
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          R2_API_HOST: "${{ secrets.R2_API_HOST }}"
          R2_ACCESS_KEY_ID: "${{ secrets.R2_ACCESS_KEY_ID }}"
          R2_SECRET_ACCESS_KEY: "${{ secrets.R2_SECRET_ACCESS_KEY }}"
          R2_ASSETS_BUCKET: "${{ env.R2_ASSETS_BUCKET }}"
          OBAN_KEY_FINGERPRINT: "${{ secrets.OBAN_KEY_FINGERPRINT }}"
          OBAN_LICENSE_KEY: "${{ secrets.OBAN_LICENSE_KEY }}"
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "docker-container://dagger-0-6-4"
        run: |
          cd magefiles
          go run main.go -w ../ ci cd
