name: "Ship It!"

concurrency:
  # There should only be able one running job per repository / branch combo.
  # We do not want multiple deploys running in parallel.
  group: ${{ github.repository }}-${{ github.ref_name }}

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

# All jobs have the same outcome. We define multiple for resiliency reasons.
jobs:
  # Trying a new backend: https://www.ubicloud.com/docs/github-actions-integration/quickstart
  dagger-on-ubicloud:
    uses: ./.github/workflows/dagger_on_ubicloud.yml
    secrets: inherit

  dagger-on-namespace:
    uses: ./.github/workflows/dagger_on_namespace.yml
    secrets: inherit

